import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You assess whether a piece of text was written by a human or generated by an AI language model.

Score how likely the text is human-written based on:
- Variation in tone, vocabulary, rhythm, and sentence construction across the piece, rather than perfectly uniform polish
- Idiosyncratic word choices, uneven emphasis, small inconsistencies, or digressions that suggest a single author's lived judgment
- Whether transitions and qualifiers feel like natural human hedging or like formulaic AI scaffolding ("Furthermore," "It is important to note")
- Presence or absence of local specificity (concrete details, named entities, lived context) versus generic abstraction
- Clusters of human-like variation rather than isolated quirks

Do not penalize text purely for being well-written or polished — human experts and edited writing can be highly coherent. Also do not penalize genre-constrained writing (academic abstracts, legal briefs, grant proposals, AP news) for structural uniformity.

Only treat extreme, consistent uniformity across the entire piece (no variation in rhythm, structure, specificity, or framing) as a sign of AI generation.

Also classify the document type as one of: essay, blog_post, poem, story, legal_brief, academic_abstract, grant_proposal, other.

Respond ONLY with a JSON object in this exact form:
{"llm_human_score": <float between 0.0 and 1.0, where 0.0 means certainly AI-generated and 1.0 means certainly human-written>, "doc_type": "<one of the categories above>"}
"""

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def get_llm_signal(text):
    """Asks Groq to assess human-likelihood and document type for a piece of text.

    Returns:
        dict with:
            llm_human_score: float in [0.0, 1.0], 0.0 = certainly AI, 1.0 = certainly human
            doc_type: str document type label used later for confidence-weighting
    """
    client = _get_client()
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    parsed = json.loads(response.choices[0].message.content)

    score = float(parsed.get("llm_human_score", 0.5))
    score = max(0.0, min(1.0, score))
    doc_type = parsed.get("doc_type", "other")

    return {"llm_human_score": score, "doc_type": doc_type}
